name: DrXAFS
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pymatgen
  - jupyter
  - ipykernel
  - pip
  - pip:
      - "numpy<2"
      - git+https://github.com/xraypy/xraylarch.git